apiVersion: apps/v1
kind: Deployment
metadata:
  name: sistema-noticias-deployment
spec:
  template: 
    metadata:
      name: sistema-noticias
      labels:
        app: sistema-noticias
    spec:
      containers:
        - name: noticias-container-deploymento
          image: aluracursos/sistema-noticias:1
          ports:
            - containerPort: 80
          envFrom:
            - configMapRef:
                name: sistema-configmap
  replicas: 2
  selector: 
    matchLabels: 
      app: sistema-noticias

#kubectl rollout history deployment sistema-noticias-deployment
#kubectl annotate deployment sistema-noticias-deployment kubernetes.io/change-cause="primeito deploy"
#kubectl rollout undo deployment sistema-noticias-deployment --to-revision=<versão a ser retornada>