apiVersion: v1
kind: Pod
metadata:
  name: portal-noticias
  labels:
    app: portal-de-noticias
spec:
  containers:
    - name: portal-noticias
      image: aluracursos/portal-noticias:1
      ports:
        - containerPort: 80