apiVersion: v1
kind: Service
metadata:
  name: svc-portal-de-noticias
spec:
  type: NodePort
  ports:
    - port: 80
      #targetport: 80
      nodePort: 30000
  selector:
    app: portal-de-noticias
  
